### ISSUE TITLE
bug-report-link support

### ISSUE THREAD

**Issue by xcwl520** [KartoffelChipss/ServerLinksZ#2]
**Describe the bug**
server.properties have a config : bug-report-link 
When I load this Plugin , the Report Server Bug not display in Server Links 
So I unload this Plugin , it display again.

**To Reproduce**
none

**Expected behavior**
Player Client shound display Report Server Bug when staff set bug-report-link in server.properties.
I want to fix it, but I don't know how. Sorry.
So I create this issue

**Screenshots**
none

**Server Setup**
 - Server Software: Paper 1.21
 - Minecraft Version 1.21
 - Plugin Version 1.0

**Additional context**

**Comment by xcwl520** [comment]
![image](https://github.com/user-attachments/assets/61443f75-c51e-44de-a3a7-ec3cb3399057)
I find the bug is on Linkmanager.java line 32,I delete it ,the Report Server Bug is display
![image](https://github.com/user-attachments/assets/0d7a87f4-3933-428e-98c3-4347c10d26f1)

**Comment by KartoffelChipss** [comment]
So if I undertand correctly, normally you the server would take the "Report Server Bug" link from the `server.properties`, but with the plugin installed it doesn't anymore.

But you can just add the link via the plugin, can't you?

**Comment by xcwl520** [comment]
ok ，my problem.I closed this issue.
