### ISSUE TITLE
Please add support for fabric servers

### ISSUE THREAD

**Issue by BITS-US** [KartoffelChipss/ServerLinksZ#4]
Please make this available for fabric servers. I run a fabric server and would love to add more links to this section for the Minecraft menu.

**Comment by KartoffelChipss** [comment]
I’m sorry, but creating a plugin for Bukkit/Spigot is significantly different from developing a mod for Fabric. I don’t have the time or interest to learn modding for Fabric, so the plugin won’t be ported to that platform.
