### ISSUE TITLE
Instead of hardcoding commands, make them customizable in config

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [KartoffelChipss/ServerLinksZ#7]
**Is your feature request related to a problem? Please describe.**
Some commands especially simple as "link" could be redefigned to have alias set in config instead of being hardcoded
for example someone could use link command to link discord accounts with discord account using well known plugin DiscordSRV

**Describe the solution you'd like**
Make commands customizable or have them a bit complex (so instead of `/link`, make them `/sllink` or with space, then it would be 1 single command `/sl` with subarguments) and not take place of some simple commands

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by aurorusmc** [comment]
You could use /discordsrv:link but I can totally agree with you.

**Comment by KartoffelChipss** [comment]
If you want the server to default to the link command of another plugin you can either use `/otherplugin:link` or you can create an alias in the `commands.yml` of your server like the following:

```lml
aliases:
  link:
  - "otherplugin:link"
```
